LOGLEVEL: DEBUG
DEBUG: False
HOST: 127.0.0.1
BACKEND_PORT: 8000
FRONTEND_PORT: 5000
REDIS_PORT: 6379
REDIS_DB: 0
ACCESS_TOKEN_EXPIRE_DAYS: 90
JWT_ALGORITHM: HS256
SECRET_KEY: d5ac699ba8c3a5618328fea541104448ed2f6eae84ed885e6b5cd9c16b318201

GP_HOST: ''
GP_PORT: 5432
GP_DATABASE: ''
GP_SCHEMA: ''
