[project]
name = "worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asyncio-atexit>=1.0.1",
    "llama-cpp-python>=0.3.9",
    "loguru>=0.7.3",
    "pydantic>=2.11.4",
    "redis==5.2.1",
]
